import type { DocumentState, StatusMetaEntry } from '../types/domain';

export const STATUS_META: Record<DocumentState, StatusMetaEntry> = {
  DRAFT: {
    label: 'Draft',
    bg: 'bg-neutral-100',
    text: 'text-neutral-700',
    borderLeft: 'border-l-2 border-l-neutral-600',
    borderStyle: 'dashed',
    textStyle: 'normal',
  },
  SUBMITTED: {
    label: 'Submitted',
    bg: 'bg-neutral-50',
    text: 'text-neutral-700',
    borderLeft: 'border-l-2 border-l-neutral-500',
    borderStyle: 'solid',
    textStyle: 'normal',
  },
  IN_WORKFLOW: {
    label: 'In Workflow',
    bg: 'bg-info-100',
    text: 'text-info-900',
    borderLeft: 'border-l-2 border-l-info-500',
    borderStyle: 'solid',
    textStyle: 'normal',
  },
  PENDING_APPROVAL: {
    label: 'Pending Approval',
    bg: 'bg-warning-100',
    text: 'text-warning-900',
    borderLeft: 'border-l-2 border-l-warning-500',
    borderStyle: 'solid',
    textStyle: 'normal',
  },
  COMPLETED: {
    label: 'Completed',
    bg: 'bg-success-100',
    text: 'text-success-900',
    borderLeft: 'border-l-2 border-l-success-500',
    borderStyle: 'solid',
    textStyle: 'normal',
  },
  RELEASED: {
    label: 'Released',
    bg: 'bg-success-100',
    text: 'text-success-900',
    borderLeft: 'border-l-2 border-l-success-300',
    borderStyle: 'solid',
    textStyle: 'normal',
  },
  ARCHIVED: {
    label: 'Archived',
    bg: 'bg-neutral-100',
    text: 'text-neutral-600',
    borderLeft: 'border-l-2 border-l-neutral-400',
    borderStyle: 'solid',
    textStyle: 'normal',
  },
  DISPOSED: {
    label: 'Disposed',
    bg: 'bg-neutral-100',
    text: 'text-neutral-600',
    borderLeft: 'border-l-2 border-l-neutral-400',
    borderStyle: 'solid',
    textStyle: 'normal',
  },
  CANCELLED: {
    label: 'Cancelled',
    bg: 'bg-neutral-100',
    text: 'text-neutral-600',
    borderLeft: 'border-l-2 border-l-neutral-400',
    borderStyle: 'solid',
    textStyle: 'line-through',
  },
  FIRST_READING: {
    label: 'First Reading',
    bg: 'bg-info-100',
    text: 'text-info-900',
    borderLeft: 'border-l-2 border-l-info-500',
    borderStyle: 'solid',
    textStyle: 'normal',
  },
  SECOND_READING: {
    label: 'Second Reading',
    bg: 'bg-info-100',
    text: 'text-info-900',
    borderLeft: 'border-l-2 border-l-info-500',
    borderStyle: 'solid',
    textStyle: 'normal',
  },
  THIRD_READING: {
    label: 'Third Reading',
    bg: 'bg-info-100',
    text: 'text-info-900',
    borderLeft: 'border-l-2 border-l-info-500',
    borderStyle: 'solid',
    textStyle: 'normal',
  },
  IN_COMMITTEE: {
    label: 'In Committee',
    bg: 'bg-info-100',
    text: 'text-info-900',
    borderLeft: 'border-l-2 border-l-info-500',
    borderStyle: 'solid',
    textStyle: 'normal',
  },
  PENDING_MAYOR: {
    label: 'Pending Mayor',
    bg: 'bg-warning-100',
    text: 'text-warning-900',
    borderLeft: 'border-l-2 border-l-warning-500',
    borderStyle: 'solid',
    textStyle: 'normal',
  },
  VETOED: {
    label: 'Vetoed',
    bg: 'bg-danger-100',
    text: 'text-danger-900',
    borderLeft: 'border-l-2 border-l-danger-500',
    borderStyle: 'solid',
    textStyle: 'normal',
  },
  OVERRIDE_PENDING: {
    label: 'Override Pending',
    bg: 'bg-warning-100',
    text: 'text-warning-900',
    borderLeft: 'border-l-2 border-l-warning-500',
    borderStyle: 'solid',
    textStyle: 'normal',
  },
  LAPSED: {
    label: 'Lapsed',
    bg: 'bg-neutral-100',
    text: 'text-neutral-700',
    borderLeft: 'border-l-2 border-l-neutral-400',
    borderStyle: 'solid',
    textStyle: 'italic',
  },
  PANLALAWIGAN_REVIEW: {
    label: 'Panlalawigan Review',
    bg: 'bg-warning-100',
    text: 'text-warning-900',
    borderLeft: 'border-l-2 border-l-warning-500',
    borderStyle: 'solid',
    textStyle: 'normal',
  },
  VALID: {
    label: 'Valid',
    bg: 'bg-success-100',
    text: 'text-success-900',
    borderLeft: 'border-l-2 border-l-success-500',
    borderStyle: 'solid',
    textStyle: 'normal',
  },
  VALID_IN_PART: {
    label: 'Valid in Part',
    bg: 'bg-warning-100',
    text: 'text-warning-900',
    borderLeft: 'border-l-2 border-l-warning-500',
    borderStyle: 'solid',
    textStyle: 'normal',
  },
  RETURNED: {
    label: 'Returned',
    bg: 'bg-danger-100',
    text: 'text-danger-900',
    borderLeft: 'border-l-2 border-l-danger-500',
    borderStyle: 'solid',
    textStyle: 'normal',
  },
  DEEMED_APPROVED: {
    label: 'Deemed Approved',
    bg: 'bg-success-100',
    text: 'text-success-900',
    borderLeft: 'border-l-2 border-l-success-300',
    borderStyle: 'dashed',
    textStyle: 'italic',
  },
  PENDING_HEARING: {
    label: 'Pending Hearing',
    bg: 'bg-warning-100',
    text: 'text-warning-900',
    borderLeft: 'border-l-2 border-l-warning-500',
    borderStyle: 'solid',
    textStyle: 'normal',
  },
  RECEIVED_SEEN: {
    label: 'Received / Seen',
    bg: 'bg-info-100',
    text: 'text-info-900',
    borderLeft: 'border-l-2 border-l-info-500',
    borderStyle: 'solid',
    textStyle: 'normal',
  },
  DISMISSED: {
    label: 'Dismissed',
    bg: 'bg-neutral-100',
    text: 'text-neutral-700',
    borderLeft: 'border-l-2 border-l-neutral-600',
    borderStyle: 'solid',
    textStyle: 'normal',
  },
  RESOLVED: {
    label: 'Resolved',
    bg: 'bg-success-100',
    text: 'text-success-900',
    borderLeft: 'border-l-2 border-l-success-500',
    borderStyle: 'solid',
    textStyle: 'normal',
  },
};
