-- ============================================================================
-- Migration: 0000_shared_create_event_bus_dead_letters.sql
-- Schema:    shared
-- Created:   2026-06-26 (TASK-INFRA-023)
-- Author:    Generated by Drizzle Kit; manually corrected pre-apply per C5 §2.2
--            Correction: CREATE SCHEMA changed to CREATE SCHEMA IF NOT EXISTS
--            for idempotent re-runs and psql executability (C5 §1, §2.4).
-- Affected schemas: shared
-- ============================================================================

CREATE SCHEMA IF NOT EXISTS "shared";
--> statement-breakpoint
CREATE TABLE "shared"."event_bus_dead_letters" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"event_id" uuid NOT NULL,
	"event_type" text NOT NULL,
	"payload" jsonb NOT NULL,
	"failed_module" text NOT NULL,
	"error_message" text NOT NULL,
	"failed_at" timestamp with time zone DEFAULT now() NOT NULL,
	"retry_count" integer DEFAULT 0 NOT NULL,
	"exhausted_at" timestamp with time zone
);
