import type { IamRepository, DbClient, DbTransaction } from './iam.types.js';

export function createIamRepository(_db: DbClient | DbTransaction): IamRepository {
  return {
    findUserById: () => { throw new Error('not implemented'); },
    findUserByUsername: () => { throw new Error('not implemented'); },
    findUserByEmail: () => { throw new Error('not implemented'); },
    createUser: () => { throw new Error('not implemented'); },
    updateUser: () => { throw new Error('not implemented'); },
    softDeleteUser: () => { throw new Error('not implemented'); },
    listUsers: () => { throw new Error('not implemented'); },
    updateLoginFailure: () => { throw new Error('not implemented'); },
    resetLoginFailure: () => { throw new Error('not implemented'); },
    findCredentialByUserId: () => { throw new Error('not implemented'); },
    createCredential: () => { throw new Error('not implemented'); },
    updateCredentialHash: () => { throw new Error('not implemented'); },
    createSession: () => { throw new Error('not implemented'); },
    findActiveSessionByUserId: () => { throw new Error('not implemented'); },
    findSessionByTokenHash: () => { throw new Error('not implemented'); },
    findSessionById: () => { throw new Error('not implemented'); },
    terminateSession: () => { throw new Error('not implemented'); },
    updateLastActivity: () => { throw new Error('not implemented'); },
    setSessionLocked: () => { throw new Error('not implemented'); },
    listSessionsByUserId: () => { throw new Error('not implemented'); },
    listAllActiveSessions: () => { throw new Error('not implemented'); },
    createRefreshToken: () => { throw new Error('not implemented'); },
    findRefreshTokenById: () => { throw new Error('not implemented'); },
    markRefreshTokenUsed: () => { throw new Error('not implemented'); },
    revokeRefreshTokensBySessionId: () => { throw new Error('not implemented'); },
    revokeRefreshTokenFamily: () => { throw new Error('not implemented'); },
    findLatestActiveRefreshTokenForSession: () => { throw new Error('not implemented'); },
    findRoleById: () => { throw new Error('not implemented'); },
    findRoleByCode: () => { throw new Error('not implemented'); },
    listActiveRoles: () => { throw new Error('not implemented'); },
    findActiveRoleAssignmentsByUserId: () => { throw new Error('not implemented'); },
    createRoleAssignment: () => { throw new Error('not implemented'); },
    revokeRoleAssignment: () => { throw new Error('not implemented'); },
    findAssignmentsByUserId: () => { throw new Error('not implemented'); },
    findConflictingTypeCodeForUser: () => { throw new Error('not implemented'); },
    findPermissionsByRoleIds: () => { throw new Error('not implemented'); },
    findMfaRecordByUserId: () => { throw new Error('not implemented'); },
  };
}
