/**
 * Shared Domain Error Codes
 *
 * Sourced from: J2 Error Handling and Response Normalization Strategy.
 */

export const DOMAIN_ERROR_CODES = {
  NOT_FOUND: 'NOT_FOUND',
  DUPLICATE_CONTROL_NUMBER: 'DUPLICATE_CONTROL_NUMBER',
  NUMBER_IS_IMMUTABLE: 'NUMBER_IS_IMMUTABLE',
  SERIES_NOT_FOUND: 'SERIES_NOT_FOUND',
  ACTIVE_DESIGNATION_EXISTS: 'ACTIVE_DESIGNATION_EXISTS',
  INVALID_WORKFLOW_TRANSITION: 'INVALID_WORKFLOW_TRANSITION',
  COMMITTEE_REPORTS_PENDING: 'COMMITTEE_REPORTS_PENDING',
  CERTIFICATION_OF_URGENCY_REQUIRED: 'CERTIFICATION_OF_URGENCY_REQUIRED',
  QUORUM_NOT_MET: 'QUORUM_NOT_MET',
  WORKFLOW_STEP_NOT_ASSIGNED: 'WORKFLOW_STEP_NOT_ASSIGNED',
  DOCUMENT_NOT_FOUND: 'DOCUMENT_NOT_FOUND',
  DOCUMENT_LOCKED: 'DOCUMENT_LOCKED',
  DOCUMENT_IS_IMMUTABLE: 'DOCUMENT_IS_IMMUTABLE',
  DOCUMENT_UNDER_LEGAL_HOLD: 'DOCUMENT_UNDER_LEGAL_HOLD',
  ROLE_COMBINATION_FORBIDDEN: 'ROLE_COMBINATION_FORBIDDEN',
  FILE_SIZE_LIMIT_EXCEEDED: 'FILE_SIZE_LIMIT_EXCEEDED',
  UNSUPPORTED_FILE_TYPE: 'UNSUPPORTED_FILE_TYPE',
  STORAGE_SERVICE_ERROR: 'STORAGE_SERVICE_ERROR',
  OCR_PROCESSING_FAILED: 'OCR_PROCESSING_FAILED',
  AUDIT_CHAIN_CORRUPTED: 'AUDIT_CHAIN_CORRUPTED',
} as const;

export type DomainErrorCode =
  (typeof DOMAIN_ERROR_CODES)[keyof typeof DOMAIN_ERROR_CODES];
